/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cadastro;

import Controller.InsumoDAO;
import Model.Insumo;
import View.formDialog.ConsultaInsumo;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author walter heitor
 */
public class telaCadastroInsumo extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroInsumo
     */
    public telaCadastroInsumo() {
        initComponents();
    }
    Insumo i = new Insumo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textDescInsumo = new javax.swing.JTextField();
        textUnidade = new javax.swing.JTextField();
        btn_cadastrar_insumo_ = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textCodProduto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btn_buscar_ = new javax.swing.JButton();
        btn_alterar_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Descrição do Produto :");

        jLabel2.setText("Unidade :");

        btn_cadastrar_insumo_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/icos/save_32px.png"))); // NOI18N
        btn_cadastrar_insumo_.setText("Cadastrar");
        btn_cadastrar_insumo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_insumo_ActionPerformed(evt);
            }
        });

        jLabel4.setText("Codigo produto:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/icos/housekeeping_32px.png"))); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_buscar_.setText("Buscar");
        btn_buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_ActionPerformed(evt);
            }
        });

        btn_alterar_.setText("Alterar");
        btn_alterar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDescInsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_alterar_)
                        .addGap(31, 31, 31)
                        .addComponent(btn_buscar_)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cadastrar_insumo_)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textDescInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar_insumo_)
                    .addComponent(jButton2)
                    .addComponent(btn_buscar_)
                    .addComponent(btn_alterar_))
                .addContainerGap(335, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(716, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrar_insumo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_insumo_ActionPerformed
        // TODO add your handling code here:
        if(textDescInsumo.getText().trim().equals("")||textCodProduto.getText().trim().equals("")||textUnidade.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Um ou mais Campos não foram inseridos!!!");
        }else{
            Insumo insumo = new Insumo(textDescInsumo.getText().trim(), Integer.parseInt(textCodProduto.getText().trim()) , 
                    Integer.parseInt(textUnidade.getText().trim()));
            try {
                InsumoDAO.getInstance().persist(insumo);
                System.out.println("Os dados foram inseridos");
            } catch (Exception e) {
                System.out.println("Os dados nao foram inseridos");
            }
            
        }      
    }//GEN-LAST:event_btn_cadastrar_insumo_ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_ActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_btn_buscar_ActionPerformed

    private void btn_alterar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar_ActionPerformed
        // TODO add your handling code here:
        alterar();
    }//GEN-LAST:event_btn_alterar_ActionPerformed
   
    public void alterar(){
        i.setDescricao_produto(textDescInsumo.getText());
        i.setCod_insumo(Integer.parseInt(textCodProduto.getText()));
        i.setUnidade(Integer.parseInt(textUnidade.getText()));
        InsumoDAO.getInstance().merge(i);
        
    }
    public void buscar(){
        ConsultaInsumo ci = new ConsultaInsumo(new JFrame(), true);
        ci.setVisible(true);
        if(ci.isConfirm()){
            i=ci.getI();
            textDescInsumo.setText(i.getDescricao_produto());
            textCodProduto.setText(Integer.toString(i.getCod_insumo()));
            textUnidade.setText(Integer.toString(i.getUnidade()));
        }
    }
    public void limpar(){
        textCodProduto.setText("");
        textDescInsumo.setText("");
        textUnidade.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroInsumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar_;
    private javax.swing.JButton btn_buscar_;
    private javax.swing.JButton btn_cadastrar_insumo_;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textCodProduto;
    private javax.swing.JTextField textDescInsumo;
    private javax.swing.JTextField textUnidade;
    // End of variables declaration//GEN-END:variables
}
