/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.formDialog;

import Controller.ClienteDAO;
import Model.Cliente;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author walter heitor
 */
public class ConsultaCliente extends javax.swing.JDialog {

    /**
     * Creates new form ConsultaCliente
     */
    private Cliente ctl;
    private boolean confirm = false;
    private int id_cli;

    public void popularTabelaClientes(List<Cliente> plistaCliente) {
        DefaultTableModel modeloTabela = new DefaultTableModel();
        this.tabelaClientes.setModel(modeloTabela);
        modeloTabela.addColumn("ID");
        modeloTabela.addColumn("Nome");
        modeloTabela.addColumn("CNPJ");
        modeloTabela.addColumn("FANTASIA");

        for (Cliente cliente : plistaCliente) {
            modeloTabela.addRow(
                    new Object[]{
                        cliente.getId_pessoa(),
                        cliente.getNome(),
                        cliente.getCnpj(),
                        cliente.getFantasia()
                    }
            );
        }

    }

    public void listarClientes() {
        List<Cliente> listaCliente = new ArrayList();
        listaCliente = ClienteDAO.getInstance().findAll();
        this.popularTabelaClientes(listaCliente);
    }

    public ConsultaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textNomeCli = new javax.swing.JTextField();
        btn_cancelar_ = new javax.swing.JButton();
        btn_confirmar_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        btnListar_ = new javax.swing.JButton();
        btn_excliuir_ = new javax.swing.JButton();
        textID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Digite o Cliente");

        btn_cancelar_.setText("Cancelar");
        btn_cancelar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_ActionPerformed(evt);
            }
        });

        btn_confirmar_.setText("Confirma");
        btn_confirmar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmar_ActionPerformed(evt);
            }
        });

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        btnListar_.setText("listar");
        btnListar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar_ActionPerformed(evt);
            }
        });

        btn_excliuir_.setText("Excluir");
        btn_excliuir_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excliuir_ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cancelar_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_confirmar_))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListar_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_excliuir_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar_)
                    .addComponent(btn_excliuir_)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar_)
                    .addComponent(btn_confirmar_))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setBounds(0, 0, 629, 362);
    }// </editor-fold>//GEN-END:initComponents
    public Cliente getCtl() {
        return ctl;
    }

    public void setCtl(Cliente ctl) {
        this.ctl = ctl;
    }

    public boolean isConfirm() {
        return confirm;
    }

    public void setConfirm(boolean confirm) {
        this.confirm = confirm;
    }

    public int getId_cli() {
        return id_cli;
    }

    public void setId_cli(int id_cli) {
        this.id_cli = id_cli;
    }


    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        // TODO add your handling code here:
        //CLIK DO MAUSE
        if (tabelaClientes.getSelectedRow() != -1) {

            ctl = ClienteDAO.getInstance().getById((int) tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0));
            textNomeCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 1).toString());
            textID.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void btnListar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar_ActionPerformed
        // TODO add your handling code here:
        listarClientes();
        tabelaClientes.getSelectedRows();
        System.out.println("linha selecionada " + tabelaClientes.getSelectedRows());
    }//GEN-LAST:event_btnListar_ActionPerformed

    private void btn_cancelar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_ActionPerformed
        // TODO add your handling code here:
        setConfirm(false);
        dispose();
    }//GEN-LAST:event_btn_cancelar_ActionPerformed

    private void btn_confirmar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmar_ActionPerformed
        // TODO add your handling code here:
        int id_cli = tabelaClientes.getSelectedRow();
        if (id_cli >= 0) {
            ctl = ClienteDAO.getInstance().getById((int) tabelaClientes.getValueAt(id_cli, 0));
            setConfirm(true);
            dispose();
        } else {
            JOptionPane.showConfirmDialog(null, "selecione o cliente", "erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_confirmar_ActionPerformed

    private void btn_excliuir_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excliuir_ActionPerformed
        // TODO add your handling code here:
        
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente remover", "Confirmação",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)
                == JOptionPane.YES_OPTION) {
            int id_cli = tabelaClientes.getSelectedRow();
            if (id_cli >= 0) {
                ctl = ClienteDAO.getInstance().getById((int) tabelaClientes.getValueAt(id_cli, 0));
                System.out.println("id cliente :"+ ctl.getId_pessoa());
                int n = (int) ctl.getId_pessoa();
                System.out.println("id e --"+n);
             //   ClienteDAO.getInstance().removeById(n);
                ClienteDAO.getInstance().removeById(Integer.parseInt(textID.getText()));
                //ClienteDAO.getInstance().remove(ctl);
                setConfirm(true);
                dispose();
            } else {
                JOptionPane.showConfirmDialog(null, "selecione o cliente", "erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_excliuir_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaCliente dialog = new ConsultaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar_;
    private javax.swing.JButton btn_cancelar_;
    private javax.swing.JButton btn_confirmar_;
    private javax.swing.JButton btn_excliuir_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNomeCli;
    // End of variables declaration//GEN-END:variables
}
