/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.formDialog;

import Controller.PedidoCompraDAO;
import Model.PedidoCompra;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author walter heitor
 */
public class ConsultaPedidoCompra extends javax.swing.JDialog {

    /**
     * Creates new form ConsultaInsumo
     */
    public ConsultaPedidoCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private PedidoCompra pc;
    private boolean confirm = false;
    private int id_pc;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPedidoCompra = new javax.swing.JTable();
        btnListar_insumo_ = new javax.swing.JButton();
        textDataEmicao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        btn_confirmar_ = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_excluir_insumo_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaPedidoCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id PedidoCompra", "Id Projeto", "Id Cliente", "DataEmicao", "ValorTotal"
            }
        ));
        tabelaPedidoCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPedidoCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPedidoCompra);

        btnListar_insumo_.setText("Listar");
        btnListar_insumo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar_insumo_ActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Emição:");

        jLabel2.setText("ID:");

        btn_confirmar_.setText("Confirmar");
        btn_confirmar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmar_ActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_excluir_insumo_.setText("Excluir");
        btn_excluir_insumo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_insumo_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDataEmicao, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_excluir_insumo_)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_confirmar_)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnListar_insumo_)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textDataEmicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir_insumo_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar_insumo_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_confirmar_)
                    .addComponent(btn_cancelar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public PedidoCompra getPc() {
        return pc;
    }

    public void setPc(PedidoCompra pc) {
        this.pc = pc;
    }

    public boolean isConfirm() {
        return confirm;
    }

    public void setConfirm(boolean confirm) {
        this.confirm = confirm;
    }

    public int getId_pc() {
        return id_pc;
    }

    public void setId_pc(int id_pc) {
        this.id_pc = id_pc;
    }
    
    
    private void btnListar_insumo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar_insumo_ActionPerformed
        // TODO add your handling code here:
        listarPedidoCompra();
    }//GEN-LAST:event_btnListar_insumo_ActionPerformed

    private void tabelaPedidoCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPedidoCompraMouseClicked
        // TODO add your handling code here:
        if (tabelaPedidoCompra.getSelectedRow() != -1) {         
            pc = PedidoCompraDAO.getInstance().getById((int) tabelaPedidoCompra.getValueAt(tabelaPedidoCompra.getSelectedRow(), 0));
            textDataEmicao.setText(tabelaPedidoCompra.getValueAt(tabelaPedidoCompra.getSelectedRow(), 3).toString());
            textID.setText(tabelaPedidoCompra.getValueAt(tabelaPedidoCompra.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_tabelaPedidoCompraMouseClicked

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        setConfirm(false);
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_confirmar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmar_ActionPerformed
        // TODO add your handling code here:
        if(tabelaPedidoCompra.getSelectedRow() >=0){
            pc = PedidoCompraDAO.getInstance().getById((int) tabelaPedidoCompra.getValueAt(tabelaPedidoCompra.getSelectedRow(), 0));
            setConfirm(true);
            dispose();
        }else {
            JOptionPane.showConfirmDialog(null, "selecione o pedidoCompra", "erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_confirmar_ActionPerformed

    private void btn_excluir_insumo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_insumo_ActionPerformed
        // TODO add your handling code here:
        excluir();
    }//GEN-LAST:event_btn_excluir_insumo_ActionPerformed
   
    public void excluir(){
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente remover", "Confirmação",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)
                == JOptionPane.YES_OPTION) {
            int id_ins = tabelaPedidoCompra.getSelectedRow();
            if (id_ins >= 0) {
                pc = PedidoCompraDAO.getInstance().getById((int) tabelaPedidoCompra.getValueAt(id_ins, 0));
                System.out.println("id pedido de compra :"+ pc.getId_pedido_compra());
                int n =  pc.getId_pedido_compra();
                System.out.println("id e --"+n);
               //PedidoCompraDAO.getInstance().removeById(n);
               // PedidoCompraDAO.getInstance().removeById(Integer.parseInt(textID.getText()));
                PedidoCompraDAO.getInstance().remove(pc);
                setConfirm(true);
                dispose();
            } else {
                JOptionPane.showConfirmDialog(null, "selecione o pedido de compra", "erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    public void listarPedidoCompra(){
        List<PedidoCompra> listaPedidiCompra = new ArrayList<>();
        listaPedidiCompra = PedidoCompraDAO.getInstance().findAll();
        this.popularTabelaPedidoCompra(listaPedidiCompra);
    }
    public void popularTabelaPedidoCompra(List<PedidoCompra> plistaInsumo){
        DefaultTableModel modeloTabela = new DefaultTableModel();
        this.tabelaPedidoCompra.setModel(modeloTabela);
        modeloTabela.addColumn("Id PedidoCompra");
        modeloTabela.addColumn("Id Projeto");
        modeloTabela.addColumn("Id Cliente");
        modeloTabela.addColumn("DataEmicao");
        modeloTabela.addColumn("ValorTotal");

        
        for(PedidoCompra pedidoCompra : plistaInsumo){
            modeloTabela.addRow( new Object[]{
                pedidoCompra.getId_pedido_compra(),
                pedidoCompra.getProjetos().getId_projeto(),
                pedidoCompra.getPessoa().getId_pessoa(),
                pedidoCompra.getDt_emicao(),
                pedidoCompra.getValor_total()

            }
            
            );
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPedidoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaPedidoCompra dialog = new ConsultaPedidoCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar_insumo_;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_confirmar_;
    private javax.swing.JButton btn_excluir_insumo_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPedidoCompra;
    private javax.swing.JTextField textDataEmicao;
    private javax.swing.JTextField textID;
    // End of variables declaration//GEN-END:variables
}
