/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.formDialog;

import Controller.ClienteDAO;
import Controller.InsumoDAO;
import Model.Insumo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author walter heitor
 */
public class ConsultaInsumo extends javax.swing.JDialog {

    /**
     * Creates new form ConsultaInsumo
     */
    public ConsultaInsumo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private Insumo i;
    private boolean confirm = false;
    private int id_ins;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaInsumo = new javax.swing.JTable();
        btnListar_insumo_ = new javax.swing.JButton();
        textDescInsumo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        btn_confirmar_ = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaInsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Insumo", "Codigo", "Descrição", "Unidade"
            }
        ));
        tabelaInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaInsumoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaInsumo);

        btnListar_insumo_.setText("Listar");
        btnListar_insumo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar_insumo_ActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição do Produto :");

        jLabel2.setText("ID:");

        btn_confirmar_.setText("Confirmar");
        btn_confirmar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmar_ActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDescInsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(btnListar_insumo_))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_confirmar_)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textDescInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnListar_insumo_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_confirmar_)
                    .addComponent(btn_cancelar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Insumo getI() {
        return i;
    }

    public void setI(Insumo i) {
        this.i = i;
    }

    public boolean isConfirm() {
        return confirm;
    }

    public void setConfirm(boolean confirm) {
        this.confirm = confirm;
    }

    public int getId_ins() {
        return id_ins;
    }

    public void setId_ins(int id_ins) {
        this.id_ins = id_ins;
    }
    
    private void btnListar_insumo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar_insumo_ActionPerformed
        // TODO add your handling code here:
        listarInsumo();
    }//GEN-LAST:event_btnListar_insumo_ActionPerformed

    private void tabelaInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaInsumoMouseClicked
        // TODO add your handling code here:
        if (tabelaInsumo.getSelectedRow() != -1) {

            i = InsumoDAO.getInstance().getById((int) tabelaInsumo.getValueAt(tabelaInsumo.getSelectedRow(), 0));
            textDescInsumo.setText(tabelaInsumo.getValueAt(tabelaInsumo.getSelectedRow(), 2).toString());
            textID.setText(tabelaInsumo.getValueAt(tabelaInsumo.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_tabelaInsumoMouseClicked

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        setConfirm(false);
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_confirmar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmar_ActionPerformed
        // TODO add your handling code here:
        if(tabelaInsumo.getSelectedRow() >=0){
            i = InsumoDAO.getInstance().getById((int) tabelaInsumo.getValueAt(tabelaInsumo.getSelectedRow(), 0));
            setConfirm(true);
            dispose();
        }else {
            JOptionPane.showConfirmDialog(null, "selecione o insumo", "erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_confirmar_ActionPerformed
    public void listarInsumo(){
        List<Insumo> listaInsumo = new ArrayList<>();
        listaInsumo = InsumoDAO.getInstance().findAll();
        this.popularTabelaInsumo(listaInsumo);
    }
    public void popularTabelaInsumo(List<Insumo> plistaInsumo){
        DefaultTableModel modeloTabela = new DefaultTableModel();
        this.tabelaInsumo.setModel(modeloTabela);
        modeloTabela.addColumn("Id Insumo");
        modeloTabela.addColumn("Codigo");
        modeloTabela.addColumn("Descrição");
        modeloTabela.addColumn("Unidade");

        
        for(Insumo insumo : plistaInsumo){
            modeloTabela.addRow( new Object[]{
                insumo.getId_insumo(),
                insumo.getCod_insumo(),
                insumo.getDescricao_produto(),
                insumo.getUnidade(),

            }
            
            );
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaInsumo dialog = new ConsultaInsumo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar_insumo_;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_confirmar_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaInsumo;
    private javax.swing.JTextField textDescInsumo;
    private javax.swing.JTextField textID;
    // End of variables declaration//GEN-END:variables
}
